server {
  listen 80;
  server_name localhost;

  location /admin/ {
    proxy_pass http://frontend-admin:5174/;
  }

  location /patient/ {
    proxy_pass http://frontend-patient:5175/;
  }

  location /api/ {
    proxy_pass http://backend:4000/api/;
  }
}
