export const ROLES = {
  SUPER_ADMIN: "super_admin",
  HOSPITAL_ADMIN: "hospital_admin",
  DOCTOR: "doctor",
  FRONTDESK: "frontdesk",
  PATIENT: "patient",
  NURSE: "nurse",
  PHARMACY: "pharmacy",
  LAB: "lab",
  BILLING: "billing",
};

export const PERMISSIONS = {
  AUTH_LOGIN: "auth.login",
  USERS_READ: "users.read",
  USERS_MANAGE: "users.manage",
  ROLES_READ: "roles.read",
  ROLES_MANAGE: "roles.manage",
  PATIENTS_READ: "patients.read",
  PATIENTS_MANAGE: "patients.manage",
  APPOINTMENTS_READ: "appointments.read",
  APPOINTMENTS_MANAGE: "appointments.manage",
  ENCOUNTERS_READ: "encounters.read",
  ENCOUNTERS_MANAGE: "encounters.manage",
  BILLING_READ: "billing.read",
  BILLING_MANAGE: "billing.manage",
  PAYMENTS_MANAGE: "payments.manage",
  REPORTS_DAILY_COLLECTIONS: "reports.daily_collections",
  AUDIT_READ: "audit.read",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.HOSPITAL_ADMIN]: Object.values(PERMISSIONS).filter(
    (permission) => permission !== PERMISSIONS.ROLES_MANAGE
  ),
  [ROLES.DOCTOR]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_MANAGE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_MANAGE,
    PERMISSIONS.ENCOUNTERS_READ,
    PERMISSIONS.ENCOUNTERS_MANAGE,
    PERMISSIONS.BILLING_READ,
  ],
  [ROLES.FRONTDESK]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_MANAGE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.PAYMENTS_MANAGE,
  ],
  [ROLES.PATIENT]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_MANAGE,
    PERMISSIONS.ENCOUNTERS_READ,
    PERMISSIONS.BILLING_READ,
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_MANAGE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_MANAGE,
    PERMISSIONS.ENCOUNTERS_READ,
    PERMISSIONS.ENCOUNTERS_MANAGE,
  ],
  [ROLES.PHARMACY]: [PERMISSIONS.AUTH_LOGIN],
  [ROLES.LAB]: [PERMISSIONS.AUTH_LOGIN, PERMISSIONS.ENCOUNTERS_READ],
  [ROLES.BILLING]: [
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.PAYMENTS_MANAGE,
    PERMISSIONS.REPORTS_DAILY_COLLECTIONS,
  ],
};
